####################################################################################
# symfony-project-template - Docker - prod Container Configuration                 #
# @author: Axel Salem                                      #
####################################################################################

# Docker-compose language version
version: '3.8'
